Update ss_libev.init

diff --git a/ss_libev.init b/ss_libev.init
--- a/ss_libev.init
+++ b/ss_libev.init
@@ -13,31 +13,38 @@
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+COLOR_RED='\E[1;31m'
+COLOR_GREEN='\E[1;32m'
+COLOR_GREEN_DEEP='\033[0;32m'
+COLOR_YELLOW='\E[1;33m'
+COLOR_BLUE='\E[1;34m'
+COLOR_PINK='\E[1;35m'
+COLOR_PINKBACK_WHITEFONT='\033[45;37m'
+COLOR_GREEN_LIGHTNING='\033[32m \033[05m'
+COLOR_END='\E[0m'
+
 # Source function library
 if [ -f /etc/rc.d/init.d/functions ]; then
     . /etc/rc.d/init.d/functions
 # Check that networking is up.
     [ ${NETWORKING} ="yes" ] || exit 0
 fi
+
 if [ -f /usr/local/bin/ss-server ]; then
-    ProgramPath=/usr/local/bin
+    BIN=/usr/local/bin/ss-server
 elif [ -f /usr/bin/ss-server ]; then
-    ProgramPath=/usr/bin
+    BIN=/usr/bin/ss-server
 fi
-ProgramName=Shadowsocks-libve
-NAME=ss-server
-BIN=${ProgramPath}/${NAME}
+ProgramName="Shadowsocks-libev"
 CONFIGFILE=/etc/shadowsocks-libev/config.json
-LOGFILE=/root/${NAME}.log
-SCRIPTNAME=/etc/init.d/shadowsocks
 PID_DIR=/var/run
 PID_FILE=${PID_DIR}/shadowsocks-libev.pid
 version="2.0"
 RET_VAL=0
 
 [ -x ${BIN} ] || exit 0
-if [ ! -r ${CONFIGFILE} ]; then
-    echo "config file ${CONFIGFILE} not found"
+if [ ! -f ${CONFIGFILE} ]; then
+    echo "${ProgramName}config file ${CONFIGFILE} not found"
     exit 1
 fi
 
@@ -49,103 +56,102 @@ if [ ! -d $PID_DIR ]; then
     fi    
 fi
 
-fun_check_run(){
-    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
-    if [ ! -z $PID ]; then
-        return 0
-    else
-        rm -f ${PID_FILE}
-        return 1
-    fi
-}
-fun_start(){
-    log_flag="$1"
-
-    if [ ! -d ${PID_DIR} ]; then
-        mkdir -p ${PID_DIR} || echo "failed creating PID directory ${PID_DIR}"; exit 1
-    fi
-    if fun_check_run; then
-        echo "${ProgramName} (pid $PID) already running."
-        return 0
-    fi
-    if [[ "${log_flag}" =~ ^[Ll][Oo][Gg]$ ]]; then
-        strLog="${LOGFILE}"
-    else
-        strLog="/dev/null"
-    fi
-    echo -n "Starting ${ProgramName}..."
-    ${BIN} -c $CONFIGFILE -u -f $PID_FILE > ${strLog} 2>&1 &
-    sleep 0.3
-    if ! fun_check_run; then
-        echo "start failed"
-        return 1
-    fi
-    echo " done"
-    fun_version
-    echo "${ProgramName} (pid $PID)is running."
-    if [[ "${log_flag}" =~ ^[Ll][Oo][Gg]$ ]]; then
-        echo "read ${LOGFILE} for log" 
-    fi
-    return 0
-}
-fun_stop(){
-
-    if fun_check_run; then
-        echo -n "Stoping ${ProgramName} (pid $PID)... "
-        kill $PID
-        if [ "$?" != 0 ] ; then
-            echo " failed"
-            exit 1
+check_running() {
+    if [ -r $PID_FILE ]; then
+        read PID < $PID_FILE
+        if [ -d "/proc/$PID" ]; then
+            return 0
         else
-            echo " done"
             rm -f $PID_FILE
+            return 1
         fi
     else
-        echo "${ProgramName} is not running."
+        return 2
     fi
-}
-fun_restart(){
-    local restart_log_flag="$1"
-    fun_stop
-    if [[ "${restart_log_flag}" =~ ^[Ll][Oo][Gg]$ ]]; then
-        fun_start log
-    else
-        fun_start
-    fi
-}
-fun_status(){
-    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
-    if [ ! -z $PID ]; then
-        echo "${ProgramName} (pid $PID) is running..."
-    else
-        echo "${ProgramName} is stopped"
-        exit 0
-    fi
-}
-fun_config(){
-    vi ${CONFIGFILE}
-}
-fun_viewconfig(){
-    cat ${CONFIGFILE}
-    echo
-}
-fun_version(){
-     echo "${ProgramName} version $(${BIN} --help | grep -i "shadowsocks-libev" | awk '{print $2}')"
 }
 
-arg1=$1
-arg2=$2
-[  -z ${arg1} ]
-case "${arg1}" in
+do_start(){
+    if [ -f $PID_FILE ]; then
+        read PID < $PID_FILE
+        echo "${ProgramName} (pid $PID) is already running."
+        exit 0
+    else
+	echo -e -n "Starting ${ProgramName}:"
+    if [ -f /root/${ProgramName}.log ]; then rm -f /root/${ProgramName}.log; fi
+	if [[ "${log_flag}" =~ ^[Ll][Oo][Gg]$ ]]; then
+            ${BIN} -v -c ${CONFIGFILE} > /root/${ProgramName}.log 2>&1 &
+	    echo $! >  $PID_FILE
+	else
+	    ${BIN} -v -c ${CONFIGFILE} -f $PID_FILE
+	fi
+    fi
+    RETVAL=$?
+    if check_running; then
+        echo -e "${COLOR_GREEN_DEEP}                                 [OK]${COLOR_END}"
+    else
+        echo -e "${COLOR_RED}                               [FAILED]${COLOR_END}"
+        RETVAL=1
+    fi
+}
+
+do_stop(){
+    echo -e -n "Stopping ${ProgramName}:"
+        if check_running; then
+            kill -9 $PID
+            echo -e "${COLOR_GREEN_DEEP}                                 [OK]${COLOR_END}"
+        else
+	    echo -e "${COLOR_RED}                               [FAILED]${COLOR_END}"
+            echo -e "${COLOR_RED}${ProgramName} not running.${COLOR_END}"
+            RETVAL=1
+        fi
+    RETVAL=$?
+    [ $RETVAL -eq 0 ]
+    rm -f $PID_FILE
+}
+
+do_status() {
+    check_running
+    case $? in
+        0)
+        echo "${ProgramName} (pid $PID) is running..."
+        ;;
+        1|2)
+        echo "${ProgramName} is stopped"
+        RETVAL=1
+        ;;
+    esac
+}
+
+do_restart() {
+    do_stop
+    do_start
+}
+
+do_config() {
+    vi ${CONFIGFILE}
+}
+
+do_viewconfig() {
+    cat ${CONFIGFILE}
+}
+
+do_version(){
+    echo -e "${ProgramName} version: ${COLOR_GREEN}$(${BIN} --help | grep -i "shadowsocks-libev" | awk '{print $2}')${COLOR_END}"
+}
+
+log_flag=$2
+case "$1" in
     start|stop|restart|status|config|viewconfig)
-        fun_${arg1} ${arg2}
+    check_running
+    do_$1
     ;;
     [vV][eE][rR][sS][iI][oO][nN]|-[vV][eE][rR][sS][iI][oO][nN]|--[vV][eE][rR][sS][iI][oO][nN]|-[vV]|--[vV])
-        fun_version
+        do_version
     ;;
     *)
-        echo "Usage: $SCRIPTNAME {start|stop|restart|status|config|viewconfig|version}"
-        RET_VAL=1
+    echo "Usage: $0 { start | stop | restart | status | config | viewconfig | version }"
+    RETVAL=1
     ;;
 esac
-exit $RET_VAL
+
+exit $RETVAL
