Update ssrr.init

diff --git a/ssrr.init b/ssrr.init
--- a/ssrr.init
+++ b/ssrr.init
@@ -12,65 +12,109 @@
 # Description:       Start or stop the ShadowsocksRR server
 ### END INIT INFO
 
-NAME=ShadowsocksRR
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+COLOR_RED='\E[1;31m'
+COLOR_GREEN='\E[1;32m'
+COLOR_GREEN_DEEP='\033[0;32m'
+COLOR_YELLOW='\E[1;33m'
+COLOR_BLUE='\E[1;34m'
+COLOR_PINK='\E[1;35m'
+COLOR_PINKBACK_WHITEFONT='\033[45;37m'
+COLOR_GREEN_LIGHTNING='\033[32m \033[05m'
+COLOR_END='\E[0m'
+ProgramName=ShadowsocksRR
 BIN=/usr/local/shadowsocksRR/shadowsocks/server.py
-CONF=/usr/local/shadowsocksRR/user-config.json
+CONFIGFILE=/usr/local/shadowsocksRR/user-config.json
+PID_DIR=/var/run
+PID_FILE=${PID_DIR}/shadowsocksr.pid
 version="2.0"
 RETVAL=0
 [ -x ${BIN} ] || exit 0
-if [ ! -r ${CONF} ]; then
-    echo "config file ${CONF} not found"
+if [ ! -f ${CONFIGFILE} ]; then
+    echo "${ProgramName}config file ${CONFIGFILE} not found"
     exit 1
 fi
+if [ ! -d $PID_DIR ]; then
+    mkdir -p $PID_DIR
+    if [ $? -ne 0 ]; then
+        echo "Creating PID directory $PID_DIR failed"
+        exit 1
+    fi    
+fi
 check_running(){
-    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
-    if [ ! -z $PID ]; then
-        return 0
+    if [ -r $PID_FILE ]; then
+        read PID < $PID_FILE
+        if [ -d "/proc/$PID" ]; then
+            return 0
+        else
+            rm -f $PID_FILE
+            return 1
+        fi
     else
-        return 1
-    fi
+        PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
+	if [ ! -z $PID ]; then
+	    return 0
+        else
+            return 1
+        fi
+    fi    
 }
 
 do_start(){
     check_running
     if [ $? -eq 0 ]; then
-        echo "$NAME (pid $PID) is already running..."
+        echo "${ProgramName} (pid $PID) is already running."
         exit 0
     else
-        $BIN -c $CONF -d start
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
-            echo "Starting $NAME success"
-        else
-            echo "Starting $NAME failed"
-        fi
+   	    echo -e -n "Starting ${ProgramName}:"
+        if [ -f /root/${ProgramName}.log ]; then rm -f /root/${ProgramName}.log; fi
+        if [[ "${log_flag}" =~ ^[Ll][Oo][Gg]$ ]]; then
+            $BIN -v -c $CONFIGFILE -d start --pid-file $PID_FILE --log-file /root/$ProgramName.log>/dev/null 2>&1  
+	    else
+            $BIN -v -c $CONFIGFILE -d start --pid-file $PID_FILE>/dev/null 2>&1  
+	    fi
+    fi
+    RETVAL=$?
+    if [ $RETVAL -eq 0 ]; then
+        echo -e "                                    [${COLOR_GREEN_DEEP}  OK  ${COLOR_END}]"
+    else
+        echo -e "                                    [${COLOR_RED}FAILED${COLOR_END}]"
+	RETVAL=1
     fi
 }
 
 do_stop(){
-    check_running
-    if [ $? -eq 0 ]; then
-        $BIN -c $CONF -d stop
+    echo -e -n "Stopping ${ProgramName}:"
+    if check_running; then
+        $BIN -v -c $CONFIGFILE -d stop --pid-file $PID_FILE>/dev/null 2>&1  
         RETVAL=$?
         if [ $RETVAL -eq 0 ]; then
-            echo "Stopping $NAME success"
+	        echo -e "                                    [${COLOR_GREEN_DEEP}  OK  ${COLOR_END}]"
         else
-            echo "Stopping $NAME failed"
+	        echo -e "                                    [${COLOR_RED}FAILED${COLOR_END}]"
+	        RETVAL=1
         fi
     else
-        echo "$NAME is stopped"
+	    echo -e "                                    [${COLOR_RED}FAILED${COLOR_END}]"
+        echo -e "${COLOR_RED}${ProgramName} not running.${COLOR_END}"
         RETVAL=1
     fi
+    RETVAL=$?
+    [ $RETVAL -eq 0 ]
+    rm -f $PID_FILE
 }
 
 do_status(){
     check_running
-    if [ $? -eq 0 ]; then
-        echo "$NAME (pid $PID) is running..."
-    else
-        echo "$NAME is stopped"
+    case $? in
+        0)
+        echo "${ProgramName} (pid $PID) is running..."
+        ;;
+        1|2)
+        echo "${ProgramName} is stopped"
         RETVAL=1
-    fi
+        ;;
+    esac
 }
 
 do_restart(){
@@ -79,20 +123,21 @@ do_restart(){
 }
 
 do_config(){
-    vi ${CONF}
+    vi ${CONFIGFILE}
 }
 
 do_viewconfig(){
-    cat ${CONF}
-    echo
+    cat ${CONFIGFILE}
 }
 
 do_version(){
     ${BIN} --version
 }
 
+log_flag=$2
 case "$1" in
     start|stop|restart|status|config|viewconfig)
+    check_running
     do_$1
     ;;
     [vV][eE][rR][sS][iI][oO][nN]|-[vV][eE][rR][sS][iI][oO][nN]|--[vV][eE][rR][sS][iI][oO][nN]|-[vV]|--[vV])
